export const FORM_ACTION = {
  FORM_START: "FORM_START",
  FORM_SUCCESS: "FORM_SUCCESS",
  FORM_FAILURE: "FORM_FAILURE",
  FORM_CLEAR: "FORM_CLEAR"
};

export const STATUS = {
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  LOADING: "LOADING",
  CLEAR: "CLEAR"
};

export const YOGA_ACTION = {
  YOGA_START: "YOGA_START",
  YOGA_SUCCESS: "YOGA_SUCCESS",
  YOGA_FAILURE: "YOGA_FAILURE",
  YOGA_CLEAR: "YOGA_CLEAR"
};